### ISSUE TITLE
翻译中的剧情统计

### ISSUE THREAD

**Issue by biuuu** [biuuu/BLHXFY#123]
剧情 | 发起日期 | 翻译
------------ | ------------- | -------------
克蕾雅sr，ssr以及泳装ssr个人角色剧情，暗贝熊泳贝熊剧情，ssr水属安剧情 | 2018/9/3 | @sakurairsora 
泳佐个人剧情，罗密欧个人剧情 | 2018/9/3 | @KoutsukiYakou 
偶像大师sidem3个联动角色 | 2018/9/3 | @arktos29 
马姬莎（万能的魔女）SSR个人剧情 | 2018/9/3 | @MAMUS-LLP 
晓之空篇，64-76已翻，77~待翻 | 2018/9/3 | @LyriaP 
9月5日之前上传鸡剧情 | 2018/9/3 | @nageBqianglelaoziXMXdeID 
贞德一套（光，暗，泳，村姑ver） | 2018/9/3 | @BigDickKyoko 
神盾、羊 的个人剧情 | 2018/9/3 | @modai-pimin 
波雷米亚个人剧情 莎拉个人剧情 沙神一期二期 | 2018/9/3 | @yakumoki 
十天众中三，四，六，七的个人剧情 | 2018/9/4 | @MAMUS-LLP 
火佐仓个人剧情 | 2018/9/4 | @lustdance 
席尔瓦，库库璐，库姆悠全版本个人剧情  席尔瓦x库库璐联携剧情  席尔瓦x库姆悠联携剧情 | 2018/9/5 | @DevilPoi 
樱花大战联动剧情 | 2018/9/6 | @Harphemaen 
十天众之二的个人剧情 | 2018/9/6 | @ninomiyanatsuki 
那炼金活动吧 | 2018/9/7 | @lustdance 
该隐ssr个人剧情 | 2018/9/7 | @Nochokyn 
狗个人剧情后一章，狗和鸡的联动剧情 | 2018.9.7 | @kozue3322 
泳裝露娜露(R) | 2018/9/7 | @mirror0420

**Comment by sakurairsora** [comment]
克蕾雅sr，ssr以及泳装ssr个人角色剧情

**Comment by KoutsukiYakou** [comment]
泳佐个人剧情，罗密欧个人剧情

**Comment by arktos29** [comment]
偶像大师sidem3个联动角色

**Comment by nageBqianglelaoziXMXdeID** [comment]
9月5日之前上传鸡剧情

**Comment by BigDickKyoko** [comment]
贞德一套（光，暗，泳，村姑ver）

**Comment by modai-pimin** [comment]
神盾个人剧情

**Comment by yakumoki** [comment]
波雷米亚个人剧情
莎拉个人剧情
沙神一期二期

**Comment by MAMUS-LLP** [comment]
十天众中三，四，六，七的个人剧情

**Comment by lustdance** [comment]
火佐仓个人剧情

**Comment by DevilPoi** [comment]
席尔瓦，库库璐，库姆悠全版本个人剧情
席尔瓦x库库璐联携剧情
席尔瓦x库姆悠联携剧情

**Comment by Harphemaen** [comment]
樱花大战联动剧情

**Comment by ninomiyanatsuki** [comment]
十天众之二的个人剧情

**Comment by ninomiyanatsuki** [comment]
职业技能翻译

**Comment by lustdance** [comment]
泳装龙姬

**Comment by lustdance** [comment]
@biuuu 看到了，那炼金活动吧

**Comment by Nochokyn** [comment]
该隐ssr个人剧情

**Comment by kozue3322** [comment]
狗个人剧情后一章，狗和鸡的联动剧情

**Comment by mirror0420** [comment]
泳裝露娜露(R)

**Comment by kozue3322** [comment]
sr鸡妹个人剧情

**Comment by AthurVer** [comment]
孤独的龙姬活动剧情

**Comment by MIZUtan** [comment]
圣德芬个人剧情「ほろ苦い記憶」和万圣节语音+万圣节主页语音（会先做万圣节的）
