### ISSUE TITLE
设定按钮说明文

### ISSUE THREAD

**Issue by shala9999** [biuuu/BLHXFY#252]
![qq 20181206104153](https://user-images.githubusercontent.com/24564547/49557755-a61f6300-f943-11e8-8e86-2004ba430586.png)
战斗等游戏中的动作比较迟缓的时候，可通过调整设定来改善

**Comment by shala9999** [comment]
![qq 20181206105810](https://user-images.githubusercontent.com/24564547/49558407-e849a400-f945-11e8-9f78-fdd4f0c7cce1.png)
好友申请设定
接受好友申请
设定是否接受好友申请
接受
好友申请
在战斗结算画面提出好友申请
提处好友申请

**Comment by shala9999** [comment]
![qq 20181206110125](https://user-images.githubusercontent.com/24564547/49558565-745bcb80-f946-11e8-8296-23286195c7d0.png)
人物介绍
向全体公开
*人物介绍的公开设定设置为“仅向好友公开”或“向好友和骑空团公开”的场合，下记项目都无法选择“全体”。
打招呼
图鉴
骑空团
好友召唤石
推荐角色
公开属性强化技能等级

按钮：不公开，仅好友，全体

**Comment by shala9999** [comment]
![qq 20181206113451](https://user-images.githubusercontent.com/24564547/49559796-f64df380-f94a-11e8-985d-6bec12a8f426.png)
技能队列
设定技能队列的表示方法
off 缩小表示 通常表示
技能效果表示设定
变更技能效果的窗口大小
off 简略表示 详细表示

**Comment by shala9999** [comment]
![qq 20181206113759](https://user-images.githubusercontent.com/24564547/49559910-6a889700-f94b-11e8-8adb-37c31a1bdd5a.png)
战斗速度
设定战斗演出的速度
加快战斗速度会导致跳过演出
标准 快进
召唤重放速度
设定全屏召唤的演出播放速度
全屏以外的召唤演出速度不会变化
标准 高速 省略
演出中的按钮显示设定
设定战斗中攻击及召唤演出时周围显示的聊天按钮和表情按钮的表示方法
off 左 右
多人战斗设定
实时通知
实时通知其他玩家造成的伤害、技能效果、敌人状态等
通知

**Comment by shala9999** [comment]
![qq 20181206115004](https://user-images.githubusercontent.com/24564547/49560390-1da5c000-f94d-11e8-84c3-3eddbb275b0c.png)
参战者使用技能通知
使用向参战者赋予效果的职业技能时，如果其他的参战者已经使用过同一个技能，则会进行通知
通知
图：因参战者已经使用过同一个技能，可能会造成效果重复。是否继续使用技能？取消/使用
跳过显示救援依赖窗口
开始多人战时跳过显示救援依赖窗口
跳过
接受救援通知
对于使用部分终端的用户，将不会在12:00~13:00,18：00~24:00进行通知
mobage的主页上会显示通知的“深夜时间”是指24：00~隔天早上6:59
按钮：全天接受，全天不接受，深夜时间不接受

**Comment by shala9999** [comment]
![qq 20181206120023](https://user-images.githubusercontent.com/24564547/49560719-85a8d600-f94e-11e8-9c03-15b68592a7dd.png)
参战者的救援依赖
针对自己发起的多人战的参战者，设定是否允许其发出救援依赖
允许发出救援依赖
通知·贡献度处显示皮肤
在实时通知及贡献度表示窗口中，设定是否显示其他参战者使用的皮肤
显示皮肤
参战者一览中显示皮肤
在参战者一览表中，设定是否显示其他参战者使用的皮肤
显示皮肤
共斗中显示皮肤
在共斗列表中，设定是否显示其他参战者使用的皮肤
显示皮肤

**Comment by biuuu** [comment]
Done.
