### ISSUE TITLE
便利设定&任务便利设定

### ISSUE THREAD

**Issue by shala9999** [biuuu/BLHXFY#254]
![default](https://user-images.githubusercontent.com/24564547/49694066-b6db0d80-fbbd-11e8-82d7-2f6e79112963.png)
道具一览设定
道具清单的过滤功能
设定道具清单的过滤功能
使用过滤功能可以更简单的查找所持道具
off 显示在左边 显示在右边
“过滤off”的场合 “过滤有效”的场合

不显示多人战房间的设定
不显示未满足参加条件的房间的设定
不显示不满足房间的招募rank条件的房间
不显示

**Comment by shala9999** [comment]
![default](https://user-images.githubusercontent.com/24564547/49694127-c149d700-fbbe-11e8-8be8-18e788ee5163.png)
武器·召唤石的回收设定
武器·召唤石的清单内所持数量达到指定数量以上时，任务结束后获得的装备自动回收。
*先回收，再自动出售·强化
清单内所持数量指定
武器所持数
召唤石所持数
*目前回收设定有效
条件设定框
回收设定
请选择用于回收的装备
武器
召唤石
*带+号的，有技能的装备不会被回收
x选择内容重置
关闭 设定

自动出售·自动强化骑空艇的设定
任务完成时获得的武器·召唤石可自动出售或强化骑空艇
*出售和强化无法同时使用
武器的自动出售·强化设定
武器出售 自动出售
强化骑空艇 自动强化
条件设定：
请设定条件
稀有度
仅N，含R
其他
含有技能武器 含天使系武器
召唤石的自动出售设定
召唤石出售 自动出售
条件设定：
稀有度
仅N，含R
其他
含天使系召唤石

**Comment by shala9999** [comment]
![default](https://user-images.githubusercontent.com/24564547/49694220-4df59480-fbc1-11e8-96ae-65108dd02a65.png)
购入金额通知功能的显示设定
购入金额通知功能的显示设定
每月使用了一定数额以上的moba硬币时，使用弹出窗口通知此事
显示
不显示“今天开始玩碧蓝”图标
不显示图标的设定
不显示“今天开始玩碧蓝”图标
*超过图标显示rank后，无论设定内容为何都不会再显示
不显示
显示内容
图标位置
左 右

**Comment by shala9999** [comment]
![default](https://user-images.githubusercontent.com/24564547/49694262-07546a00-fbc2-11e8-90f0-e947ecff09ff.png)
对话场景设定
演出内容自动播放
对话场景中的演出内容会自动进行
自动播放
文本内容一齐显示
文本内容将不会逐字显示而是一齐显示
一齐显示
任务设定
任务的活动skip
跳过已完成的任务的对话场景
跳过
跳过冒险部分
跳过任务中的冒险部分
跳过
不跳过时会有演出
跳过时只显示获得道具的结果

**Comment by shala9999** [comment]
![default](https://user-images.githubusercontent.com/24564547/49694304-f35d3800-fbc2-11e8-8329-3772d3e3e3b3.png)
战斗开始时编队内容处的显示内容
变更战斗前选择队伍画面处的情报内容
技能 加护效果
设定为“技能”的场合
设定为“加护效果”的场合

敌人有特殊能力时显示警告
变更任务中有拥有特定属性伤害耐性的能力的敌人登场时，在战斗开始前显示的的警告的设定
off 仅前卫队员 含后备队员
编队中“前卫队员”或“含后备队员的全部队员”中如果包括属性不利的角色，则显示此警告
显示内容
*任务未完成的场合，无论设定内容为何都会显示

**Comment by shala9999** [comment]
![default](https://user-images.githubusercontent.com/24564547/49694373-0a505a00-fbc4-11e8-9558-5b7382022096.png)
战斗前画面中切换auto
设定是否在战斗前画面使用auto战斗切换功能
off on 常时on
设定为“on”时，在战斗前画面点击屏幕一次会显示确认是否需要auto战斗，再点击一次auto战斗功能启动
设定为“常时on”时，在战斗前画面点击屏幕一次auto战斗功能即可启动

**Comment by shala9999** [comment]
![default](https://user-images.githubusercontent.com/24564547/49694551-518c1a00-fbc7-11e8-951f-c1fa9ece7b3c.png)
表情组显示设定
选择表情组的显示方法
可变更表情的显示顺序，表情图标
3页 5页 无履历
表情组限制为3页，第一页上最多显示4个最近使用的表情
最近使用的表情显示于此，本部分无法编辑
表情组限制为5页，第一页上最多显示12个最近使用的表情
最近使用的表情显示于此，本部分无法编辑
表情组限制为4页，不显示最近使用的表情
显示表情
设定多人战中是否显示其他玩家的表情
显示表情
有声表情设定
设定多人战中自己发出或收到的有声表情是否播放声音
播放声音

**Comment by shala9999** [comment]
![default](https://user-images.githubusercontent.com/24564547/49694602-4d143100-fbc8-11e8-8aff-b3bdca7c10e2.png)
主页设定
按钮设定
切换主页上显示的“强化”按钮和“共斗”按钮
选择中
主页BGM设定
设定主页上显示的角色或皮肤带有专用BGM的场合是否播放专用BGM
主页横幅显示设定
在主页上显示“阿卡姆转世”的横幅
显示

**Comment by shala9999** [comment]
![default](https://user-images.githubusercontent.com/24564547/49694753-0ffd6e00-fbcb-11e8-845a-f86c9afe4181.png)
切换职业

**Comment by shala9999** [comment]
![default](https://user-images.githubusercontent.com/24564547/49694767-55ba3680-fbcb-11e8-967f-f33bd9af712b.png)
这个应该是编队组管理

**Comment by zhtdsg** [comment]
你好,pc上似乎没有用
