### ISSUE TITLE
开启插件后翻译英文文本为日文

### ISSUE THREAD

**Issue by Koumo-OS** [biuuu/BLHXFY#297]
默认设置语言为英文，前几天都好好的，能把英文翻成中文，但今天打开后突然把英文变成了原本的日文，如果关闭脚本的话则显示为原有的英文，请问前辈这如何解决_(:з」∠)_

![2019-08-22_232354](https://user-images.githubusercontent.com/49365204/63527884-785f6600-c534-11e9-9c8f-777fcb13eaf4.png)
![2019-08-22_232416](https://user-images.githubusercontent.com/49365204/63527907-8319fb00-c534-11e9-82de-ffabf1e01400.png)

**Comment by Koumo-OS** [comment]
今天无论是刷新、重新打开插件还是开启的新的lovelive剧情章节都还是如此，但是前几天翻译都是好的，而且其他界面翻译还是正常的
![2019-08-22_233006](https://user-images.githubusercontent.com/49365204/63528203-181cf400-c535-11e9-8331-53fee196c599.png)
![2019-08-22_233024](https://user-images.githubusercontent.com/49365204/63528209-1b17e480-c535-11e9-8df9-55ca5b019aab.png)

**Comment by Koumo-OS** [comment]
我尝试着重启浏览器还是不行，最后我试着清空了浏览数据，删掉脚本重装之后好了_(:з」∠)_

**Comment by biuuu** [comment]
_(:з」∠)_不知道发生了什么

**Comment by biuuu** [comment]
不过，建议由日语版，机翻会准确些。
日语版的界面翻译也多些。
