### ISSUE TITLE
Everything is in chinese (?)

### ISSUE THREAD

**Issue by Darudado** [biuuu/BLHXFY#300]
Everything is in chinese. English translations?

**Comment by biuuu** [comment]
[Answer to this question](https://translate.google.com/#view=home&op=translate&sl=auto&tl=en&text=%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E6%98%AF%E7%94%A8%E6%9D%A5%E6%8A%8A%E4%B8%80%E4%B8%AA%E7%BD%91%E9%A1%B5%E6%B8%B8%E6%88%8F%E4%BB%8E%E6%97%A5%E8%AF%AD%E7%BF%BB%E8%AF%91%E6%88%90%E4%B8%AD%E6%96%87%EF%BC%8C%0A%E6%89%80%E4%BB%A5%E8%BF%99%E9%87%8C%E5%8F%AA%E6%9C%89%E4%B8%AD%E6%96%87%E8%AF%B4%E6%98%8E%E3%80%82)
