### ISSUE TITLE
新追加的游戏内设定内容翻译

### ISSUE THREAD

**Issue by shala9999** [biuuu/BLHXFY#305]
![图片](https://user-images.githubusercontent.com/24564547/69424535-d97d1c80-0d63-11ea-8c06-dbb796660cad.png)
回合处理待机设定
在处理直前回合时允许使用技能队列。
![图片](https://user-images.githubusercontent.com/24564547/69424631-134e2300-0d64-11ea-8b21-4584d9d7669e.png)
切换战斗中表示出来的AUTO按钮。
选择FULLAUTO时会自动使用攻击/技能。
详细内容请确认HELP内容。
变更设定后会适用到所有任务中。
通常     FULL       HELP

**Comment by shala9999** [comment]
主页设定
![图片](https://user-images.githubusercontent.com/24564547/69424771-63c58080-0d64-11ea-850b-9cd6f53259a0.png)
在首页显示“赌场”横幅
显示

**Comment by shala9999** [comment]
便利设定
![图片](https://user-images.githubusercontent.com/24564547/69425223-84daa100-0d65-11ea-80d1-63ec91c88d1f.png)
列表·仓库的分类设定共通化
列表的分类设定共通化
可将武器·召唤石的排列顺序·缩小范围的设定与[卖出][仓库][回收]共通。
共通
*武器·召唤石按照各自的设定共通。
*元素化无法与武器·召唤石设定共通。
---
仓库的分类设定共通化
可将武器·召唤石仓库的排列顺序·缩小范围的设定与[卖出][仓库][回收]共通。
共通
*武器·召唤石仓库按照各自的设定共通。
*元素化无法与武器·召唤石仓库设定共通。

**Comment by biuuu** [comment]
https://github.com/BLHXFY-Group/BLHXFY/blob/master/data/etc/common-html.csv
修改这个文件，添加类似下面的行内容：
`/setting,マイページにおける「強化」ボタンと「共闘」ボタンの表示を切り替えます,切换主页上显示的“强化”按钮和“共斗”按钮,`
