### ISSUE TITLE
连接彩云小译好像有些问题

### ISSUE THREAD

**Issue by winfet** [biuuu/BLHXFY#307]
userscript.html?id=5e952db9-3f26-4898-8905-e78d93f4e2a0:9390 
TypeError: Cannot read property 'cyweb_token' of null
    at testCookies (userscript.html?id=5e952db9-3f26-4898-8905-e78d93f4e2a0:9161)
    at async translator (userscript.html?id=5e952db9-3f26-4898-8905-e78d93f4e2a0:9220)
    at async Promise.all (/index 0)
    at async caiyunTrans (userscript.html?id=5e952db9-3f26-4898-8905-e78d93f4e2a0:9382)

**Comment by winfet** [comment]
彩云小译已经登录了

**Comment by biuuu** [comment]
可能加载 https://blhx.danmu9.com/blhxfy/manifest.json 失败了
ctrl + f5 刷新试试

**Comment by wengyusu** [comment]
同样的问题，清缓存无效

**Comment by biuuu** [comment]
看下 NETWORK 栏里 https://blhx.danmu9.com/blhxfy/manifest.json 是否加载失败。
如果是的话，考虑把 blhx.danmu9.com 这个域名加到你的代理里。

**Comment by wengyusu** [comment]
加载是正常的200，但是console里还是会报 
TypeError: Cannot read property 'cyweb_token' of null

**Comment by biuuu** [comment]
加QQ群详细看看？
115339945

**Comment by biuuu** [comment]
@winfet 试试完全关闭浏览器后，再打开会不会好

**Comment by winfet** [comment]
时好时坏,正在寻找规律

**Comment by winfet** [comment]
现在好像没问题了

**Comment by biuuu** [comment]
https://github.com/biuuu/BLHXFY/commit/8c11eaa7d93ecb3c61706c3a0d11bba37423ea92
可能是这个问题引起的，更新到新版后应该不会再出现了。
