### ISSUE TITLE
提示彩云小译超出使用次数，求问如何解决

### ISSUE THREAD

**Issue by Koumo-OS** [biuuu/BLHXFY#320]
https://tva2.sinaimg.cn/large/c12689b8ly1gdbtnzwzh3j20hv0px4ia.jpg
第一次遇到这种提示，尝试进行登录、更换翻译api和开关脚本都没有用，请问这是本月的翻译次数用完了吗？

**Comment by biuuu** [comment]
新版chrome可能无法获取跨域cookies，导致彩云小译登录检测失败。
![](https://user-images.githubusercontent.com/10892119/77991283-04046500-7356-11ea-95f4-bf4b4a4bcc87.png)
可以尝试修改chrome设置。

**Comment by Koumo-OS** [comment]
> 
> 
> 新版chrome可能无法获取跨域cookies，导致彩云小译登录检测失败。
> ![](https://user-images.githubusercontent.com/10892119/77991283-04046500-7356-11ea-95f4-bf4b4a4bcc87.png)
> 可以尝试修改chrome设置。

主要是之前一直用的好好的，也没有更新chrome就出现这个问题了，请问如何修改chrome设置以尝试解决呢？

**Comment by biuuu** [comment]
上面的回复里有张截图，你有加载出来吗

**Comment by Koumo-OS** [comment]
> 
> 
> 上面的回复里有张截图，你有加载出来吗

把飞机换到全局之后看到了，修改设置后问题已解决，感谢指点
