### ISSUE TITLE
关于翻译出现undefined的问题

### ISSUE THREAD

**Issue by liuyan3176** [biuuu/BLHXFY#43]
文本重复显示undefinedWhatdefined undefinedis undefinedGreaundefined 这种字符
角色姓名倒是翻译了，例如阿碧这种
重复了大概十几个对话后，就变为了英文。
而纯情狐的剧情，则是十几个对话重复 未定义 未定义 这种中文，中间夹杂日文字符，之后就变为了英文
65章的剧情没出现这个问题，火大奶也没这个问题,,

**Comment by biuuu** [comment]
@liuyan3176 
这是有段时间 noun.csv 文件里的空行导致的问题，已经修复。
但已经保存的翻译文件不会自动清除。
清空本地数据目录下的 scenario 文件夹就好了。
