### ISSUE TITLE
Node v10.5.0下yarn install会出现upath依赖错误

### ISSUE THREAD

**Issue by KurumiSerori** [biuuu/BLHXFY#79]
> Mbp:BLHXFY me$ yarn install
> yarn install v1.7.0
> [1/4] 🔍  Resolving packages...
> [2/4] 🚚  Fetching packages...
> error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
> error Found incompatible module
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

如果换用`yarn install --ignore-engines`或者去掉`yarn.lock`中与`upath`有关的几行则会在编译/打包的时候产生很多问题，
还试着删除目录下的`node_modules/`, `package-lock.json` & `yarn.lock`再install，

> [4/4] 📃  Building fresh packages...
> [1/2] ⡀ fsevents
> [2/2] ⡀ electron

> [4/4] 📃  Building fresh packages...
> success Saved lockfile.
> $ electron-builder install-app-deps
>   • electron-builder version=20.17.1
>   • loaded configuration file=/Users/kurumi/Projects/github/BLHXFY/electron-builder.json
> Error: Unresolved node modules: react

之后出现找不到`Error: Unresolved node modules: react`的错误，是不是需要添加react依赖？

anodynos/upath#14
airbnb/enzyme#1637

**Comment by KurumiSerori** [comment]
删除`node_modules/`和`yarn.lock`后，通过`yarn add react`解决了。

**Comment by biuuu** [comment]
https://github.com/biuuu/BLHXFY/pull/80
升级了依赖 upath 的模块，这样应该可以用 yarn install 了
